### ISSUE TITLE
laSV libs does not compile with zlib 1.2.8

### ISSUE THREAD

**Issue by d-cameron** [JialiUMassWengLab/laSV#1]
Running install.sh results in the following error:

```
if test -e string_buffer.o; then rm string_buffer.o; fi
if test -e libstrbuf.a; then rm libstrbuf.a; fi
if test -e strbuf_test; then rm strbuf_test; fi
for file in ; do rm -r $file; done
for file in ; do rm $file; done
/usr/bin/cc -Wall -Wextra -O3 -c string_buffer.c -o string_buffer.o
string_buffer.c: In function âstrbuf_gzputsâ:
string_buffer.c:522: warning: passing argument 1 of âgzputsâ from incompatible pointer type
/usr/local/bioinf/include/zlib.h:1364: note: expected âgzFileâ but argument is of type âstruct gzFile_s **â
string_buffer.c: In function âstrbuf_gzwriteâ:
string_buffer.c:527: warning: passing argument 1 of âgzwriteâ from incompatible pointer type
/usr/local/bioinf/include/zlib.h:1341: note: expected âgzFileâ but argument is of type âstruct gzFile_s **â
string_buffer.c: In function âstrbuf_gzreadâ:
string_buffer.c:690: warning: passing argument 1 of âgzgetsâ from incompatible pointer type
/usr/local/bioinf/include/zlib.h:1372: note: expected âgzFileâ but argument is of type âstruct gzFile_s **â
string_buffer.c: In function âstrbuf_gzreadlineâ:
string_buffer.c:721: warning: passing argument 1 of âgzgetsâ from incompatible pointer type
/usr/local/bioinf/include/zlib.h:1372: note: expected âgzFileâ but argument is of type âstruct gzFile_s **â
string_buffer.c: In function âstrbuf_gzskip_lineâ:
string_buffer.c:777: error: request for member âhaveâ in something not a structure or union
string_buffer.c:777: error: request for member âhaveâ in something not a structure or union
string_buffer.c:777: error: request for member âposâ in something not a structure or union
string_buffer.c:777: warning: left-hand operand of comma expression has no effect
string_buffer.c:777: error: request for member ânextâ in something not a structure or union
string_buffer.c:777: warning: left-hand operand of comma expression has no effect
string_buffer.c:777: warning: passing argument 1 of âgzgetcâ from incompatible pointer type
/usr/local/bioinf/include/zlib.h:1391: note: expected âgzFileâ but argument is of type âstruct gzFile_s **â
make: *** [all] Error 1
```

seq_file also results in a compilation errors.

Downloading https://github.com/noporpoise/seq_file from source _does_ compile, but a diff indicates that the master is different to the version included in laSV so I'm not sure how to proceed.

Is there anything I can do as a user to fix these issues?

**Comment by JialiUMassWengLab** [comment]
The zlib version issue is resolved. It's compatible with zlib 1.2.8 now.
